# This is a basic workflow to help you get started with Actions

name: windows test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs setenv on Windows
      - name: Run a one-line script
        shell: cmd
        run: dir && cd && call ./setenv.bat
        if: ${{ runner.os == 'Windows' }} Linux, Windows, or macOS

      # Runs setenv on macOS
      - name: Run a one-line script
        shell: bash
        run: ls &&  ./setenv.sh
        if: ${{ runner.os == 'macOS' || runner.os == 'Linux' }}
